package uemg.view;

import uemg.control.LeitoresController;


public class Leitores extends javax.swing.JFrame {
    
    public Leitores() {
        initComponents();
        btnEditar.setFocusable(false);
        btnExcluir.setFocusable(false);
        btnGravar.setFocusable(false);
        btnOk.setFocusable(false);
        btnSelect.setFocusable(false);
        btnVoltar.setFocusable(false);
        /*
        Leitores l = new Leitores();
        LeitoresController lc = new LeitoresController(l);
        
        l.setVisible(true);
        l.setLocationRelativeTo(l);*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pLeitores = new javax.swing.JPanel();
        lSair = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        pDados = new javax.swing.JPanel();
        lNome = new javax.swing.JLabel();
        lCpf = new javax.swing.JLabel();
        lEmail = new javax.swing.JLabel();
        lTelefone = new javax.swing.JLabel();
        lEndereco = new javax.swing.JLabel();
        ftfCpf = new javax.swing.JFormattedTextField();
        txfEmail = new javax.swing.JTextField();
        txfEndereco = new javax.swing.JTextField();
        txfNome = new javax.swing.JTextField();
        ftfTelefone = new javax.swing.JFormattedTextField();
        pRegistros = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dgLeitores = new javax.swing.JTable();
        pOperacoes = new javax.swing.JPanel();
        btnOk = new javax.swing.JButton();
        btnGravar = new javax.swing.JButton();
        btnSelect = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pLeitores.setBackground(new java.awt.Color(102, 0, 0));

        lSair.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        lSair.setForeground(new java.awt.Color(255, 255, 255));
        lSair.setText("X");
        lSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lSairMouseClicked(evt);
            }
        });

        btnVoltar.setBackground(new java.awt.Color(102, 0, 0));
        btnVoltar.setForeground(new java.awt.Color(255, 255, 255));
        btnVoltar.setText("VOLTAR");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        pDados.setBackground(new java.awt.Color(102, 0, 0));
        pDados.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        pDados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lNome.setForeground(new java.awt.Color(255, 255, 255));
        lNome.setText("Nome:");
        pDados.add(lNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));
        lNome.getAccessibleContext().setAccessibleName("Nome");

        lCpf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lCpf.setForeground(new java.awt.Color(255, 255, 255));
        lCpf.setText("CPF:");
        pDados.add(lCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        lEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lEmail.setForeground(new java.awt.Color(255, 255, 255));
        lEmail.setText("E-mail:");
        pDados.add(lEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        lTelefone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lTelefone.setForeground(new java.awt.Color(255, 255, 255));
        lTelefone.setText("Telefone:");
        pDados.add(lTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        lEndereco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lEndereco.setForeground(new java.awt.Color(255, 255, 255));
        lEndereco.setText("Endereço:");
        pDados.add(lEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        ftfCpf.setBackground(new java.awt.Color(102, 0, 0));
        ftfCpf.setForeground(new java.awt.Color(255, 255, 255));
        try {
            ftfCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        pDados.add(ftfCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 252, -1));

        txfEmail.setBackground(new java.awt.Color(102, 0, 0));
        txfEmail.setForeground(new java.awt.Color(255, 255, 255));
        pDados.add(txfEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 252, -1));

        txfEndereco.setBackground(new java.awt.Color(102, 0, 0));
        txfEndereco.setForeground(new java.awt.Color(255, 255, 255));
        pDados.add(txfEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 252, -1));

        txfNome.setBackground(new java.awt.Color(102, 0, 0));
        txfNome.setForeground(new java.awt.Color(255, 255, 255));
        pDados.add(txfNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 252, -1));

        ftfTelefone.setBackground(new java.awt.Color(102, 0, 0));
        ftfTelefone.setForeground(new java.awt.Color(255, 255, 255));
        try {
            ftfTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        pDados.add(ftfTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 252, -1));

        pRegistros.setBackground(new java.awt.Color(102, 0, 0));
        pRegistros.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registros", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        dgLeitores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "CPF", "E-mail", "Telefone", "Endereço"
            }
        ));
        jScrollPane1.setViewportView(dgLeitores);

        javax.swing.GroupLayout pRegistrosLayout = new javax.swing.GroupLayout(pRegistros);
        pRegistros.setLayout(pRegistrosLayout);
        pRegistrosLayout.setHorizontalGroup(
            pRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pRegistrosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE)
                .addContainerGap())
        );
        pRegistrosLayout.setVerticalGroup(
            pRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pRegistrosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                .addContainerGap())
        );

        pOperacoes.setBackground(new java.awt.Color(102, 0, 0));
        pOperacoes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Operações", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        pOperacoes.setForeground(new java.awt.Color(255, 255, 255));

        btnOk.setBackground(new java.awt.Color(102, 0, 0));
        btnOk.setForeground(new java.awt.Color(255, 255, 255));
        btnOk.setText("OK");

        btnGravar.setBackground(new java.awt.Color(102, 0, 0));
        btnGravar.setForeground(new java.awt.Color(255, 255, 255));
        btnGravar.setText("GRAVAR");

        btnSelect.setBackground(new java.awt.Color(102, 0, 0));
        btnSelect.setForeground(new java.awt.Color(255, 255, 255));
        btnSelect.setText("PESQUISAR");

        btnEditar.setBackground(new java.awt.Color(102, 0, 0));
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setText("EDITAR");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setBackground(new java.awt.Color(102, 0, 0));
        btnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluir.setText("EXCLUIR");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pOperacoesLayout = new javax.swing.GroupLayout(pOperacoes);
        pOperacoes.setLayout(pOperacoesLayout);
        pOperacoesLayout.setHorizontalGroup(
            pOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(pOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pOperacoesLayout.createSequentialGroup()
                    .addGap(0, 57, Short.MAX_VALUE)
                    .addGroup(pOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 58, Short.MAX_VALUE)))
        );
        pOperacoesLayout.setVerticalGroup(
            pOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(pOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pOperacoesLayout.createSequentialGroup()
                    .addGap(0, 9, Short.MAX_VALUE)
                    .addComponent(btnOk)
                    .addGap(7, 7, 7)
                    .addComponent(btnGravar)
                    .addGap(7, 7, 7)
                    .addComponent(btnSelect)
                    .addGap(7, 7, 7)
                    .addComponent(btnEditar)
                    .addGap(7, 7, 7)
                    .addComponent(btnExcluir)
                    .addGap(0, 9, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout pLeitoresLayout = new javax.swing.GroupLayout(pLeitores);
        pLeitores.setLayout(pLeitoresLayout);
        pLeitoresLayout.setHorizontalGroup(
            pLeitoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLeitoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pLeitoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pRegistros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pLeitoresLayout.createSequentialGroup()
                        .addComponent(pDados, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pOperacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pLeitoresLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pLeitoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lSair, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnVoltar, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        pLeitoresLayout.setVerticalGroup(
            pLeitoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLeitoresLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(lSair)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pLeitoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pDados, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                    .addComponent(pOperacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pRegistros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        getContentPane().add(pLeitores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 610));

        setSize(new java.awt.Dimension(729, 599));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lSairMouseClicked
        dispose();
    }//GEN-LAST:event_lSairMouseClicked

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        Menu m = new Menu();
        m.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcluirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnEditar;
    public javax.swing.JButton btnExcluir;
    public javax.swing.JButton btnGravar;
    public javax.swing.JButton btnOk;
    public javax.swing.JButton btnSelect;
    public javax.swing.JButton btnVoltar;
    public javax.swing.JTable dgLeitores;
    public javax.swing.JFormattedTextField ftfCpf;
    public javax.swing.JFormattedTextField ftfTelefone;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lCpf;
    private javax.swing.JLabel lEmail;
    private javax.swing.JLabel lEndereco;
    private javax.swing.JLabel lNome;
    private javax.swing.JLabel lSair;
    private javax.swing.JLabel lTelefone;
    private javax.swing.JPanel pDados;
    private javax.swing.JPanel pLeitores;
    private javax.swing.JPanel pOperacoes;
    private javax.swing.JPanel pRegistros;
    public javax.swing.JTextField txfEmail;
    public javax.swing.JTextField txfEndereco;
    public javax.swing.JTextField txfNome;
    // End of variables declaration//GEN-END:variables
}
