/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uemg.view;

import uemg.control.LoginController;

/**
 *
 * @author Adalberto
 */
public class Login extends javax.swing.JFrame {

    private LoginController control;
    
    public Login() {
        initComponents();
        btnConfirmar.setFocusable(false);
        control = new LoginController(this, null); // Substitua 'null' pelo objeto 'Menu' apropriado, se necessário
        control.setM(new Menu());
        control.setL(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pLibraryIcon = new javax.swing.JPanel();
        lTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taSubtitulo = new javax.swing.JTextArea();
        pLogin = new javax.swing.JPanel();
        lSair = new javax.swing.JLabel();
        pLoginSubmenu = new javax.swing.JPanel();
        lUsuario = new javax.swing.JLabel();
        lTitLogin = new javax.swing.JLabel();
        lSenha = new javax.swing.JLabel();
        txfUsuario = new javax.swing.JTextField();
        pfSenha = new javax.swing.JPasswordField();
        btnConfirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela de login");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pLibraryIcon.setBackground(new java.awt.Color(255, 255, 255));

        lTitulo.setFont(new java.awt.Font("Onyx", 0, 48)); // NOI18N
        lTitulo.setText("Biblioteca Universitária");
        lTitulo.setToolTipText("");

        taSubtitulo.setBackground(new java.awt.Color(255, 255, 255));
        taSubtitulo.setColumns(20);
        taSubtitulo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        taSubtitulo.setRows(5);
        taSubtitulo.setText("                    Seja bem-vindo (a) a nossa Biblioteca Universitária.\n     Esse projeto foi desenvolvido pelos alunos do curso de Engenharia da \n     Computação da Universidade do Estado de Minas Gerais e tem como \n     objetivo a aprovação na matéria de Programação Orientada a Objetos.\n\n     Os desenvolvedores do sistema foram:\n\n     -Front-end:\n     José Costa de Macedo Júnior e Marcos Vinicius de A. Pimenta.\n\n     -Back-end: \n     Adalberto Soares Oliveira e Pedro Henrique de Souza Silva.\n\n     -BD e correção de bugs:\n     Gabriel Eduardo de Oliveira Mendonça.\n\n     Fonte disponível em: github.com/soaresAdalberto");
        taSubtitulo.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        taSubtitulo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        taSubtitulo.setEnabled(false);
        jScrollPane1.setViewportView(taSubtitulo);

        javax.swing.GroupLayout pLibraryIconLayout = new javax.swing.GroupLayout(pLibraryIcon);
        pLibraryIcon.setLayout(pLibraryIconLayout);
        pLibraryIconLayout.setHorizontalGroup(
            pLibraryIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLibraryIconLayout.createSequentialGroup()
                .addGroup(pLibraryIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pLibraryIconLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pLibraryIconLayout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(lTitulo)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        pLibraryIconLayout.setVerticalGroup(
            pLibraryIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLibraryIconLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getContentPane().add(pLibraryIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 470));

        pLogin.setBackground(new java.awt.Color(102, 0, 0));

        lSair.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        lSair.setForeground(new java.awt.Color(255, 255, 255));
        lSair.setText("X");
        lSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lSairMouseClicked(evt);
            }
        });

        pLoginSubmenu.setBackground(new java.awt.Color(102, 0, 0));
        pLoginSubmenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        lUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lUsuario.setText("Usuário:");

        lTitLogin.setFont(new java.awt.Font("Rockwell Condensed", 0, 24)); // NOI18N
        lTitLogin.setForeground(new java.awt.Color(255, 255, 255));
        lTitLogin.setText("LOGIN");

        lSenha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lSenha.setForeground(new java.awt.Color(255, 255, 255));
        lSenha.setText("Senha:");

        txfUsuario.setBackground(new java.awt.Color(102, 0, 0));
        txfUsuario.setForeground(new java.awt.Color(255, 255, 255));

        pfSenha.setBackground(new java.awt.Color(102, 0, 0));
        pfSenha.setForeground(new java.awt.Color(255, 255, 255));

        btnConfirmar.setBackground(new java.awt.Color(102, 0, 0));
        btnConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmar.setText("CONFIRMAR");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pLoginSubmenuLayout = new javax.swing.GroupLayout(pLoginSubmenu);
        pLoginSubmenu.setLayout(pLoginSubmenuLayout);
        pLoginSubmenuLayout.setHorizontalGroup(
            pLoginSubmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLoginSubmenuLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pLoginSubmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pLoginSubmenuLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lTitLogin)
                        .addGap(101, 101, 101))
                    .addGroup(pLoginSubmenuLayout.createSequentialGroup()
                        .addGroup(pLoginSubmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lUsuario)
                            .addComponent(lSenha))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pLoginSubmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pfSenha)
                            .addComponent(txfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pLoginSubmenuLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(btnConfirmar)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        pLoginSubmenuLayout.setVerticalGroup(
            pLoginSubmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLoginSubmenuLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(lTitLogin)
                .addGap(81, 81, 81)
                .addGroup(pLoginSubmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lUsuario)
                    .addComponent(txfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(pLoginSubmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lSenha)
                    .addComponent(pfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(btnConfirmar)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pLoginLayout = new javax.swing.GroupLayout(pLogin);
        pLogin.setLayout(pLoginLayout);
        pLoginLayout.setHorizontalGroup(
            pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLoginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lSair)
                .addGap(17, 17, 17))
            .addGroup(pLoginLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(pLoginSubmenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        pLoginLayout.setVerticalGroup(
            pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLoginLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lSair, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pLoginSubmenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(pLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 340, 470));

        setSize(new java.awt.Dimension(897, 468));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lSairMouseClicked
        dispose();
    }//GEN-LAST:event_lSairMouseClicked

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        control.logar();
    }//GEN-LAST:event_btnConfirmarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lSair;
    private javax.swing.JLabel lSenha;
    private javax.swing.JLabel lTitLogin;
    private javax.swing.JLabel lTitulo;
    private javax.swing.JLabel lUsuario;
    private javax.swing.JPanel pLibraryIcon;
    private javax.swing.JPanel pLogin;
    private javax.swing.JPanel pLoginSubmenu;
    private javax.swing.JPasswordField pfSenha;
    private javax.swing.JTextArea taSubtitulo;
    private javax.swing.JTextField txfUsuario;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the control
     */
    public LoginController getControl() {
        return control;
    }

    /**
     * @param control the control to set
     */
    public void setControl(LoginController control) {
        this.control = control;
    }

    /**
     * @return the btnConfirmar
     */
    public javax.swing.JButton getBtnConfirmar() {
        return btnConfirmar;
    }

    /**
     * @param btnConfirmar the btnConfirmar to set
     */
    public void setBtnConfirmar(javax.swing.JButton btnConfirmar) {
        this.btnConfirmar = btnConfirmar;
    }

    /**
     * @return the jScrollPane1
     */
    public javax.swing.JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    /**
     * @param jScrollPane1 the jScrollPane1 to set
     */
    public void setjScrollPane1(javax.swing.JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    /**
     * @return the lSair
     */
    public javax.swing.JLabel getlSair() {
        return lSair;
    }

    /**
     * @param lSair the lSair to set
     */
    public void setlSair(javax.swing.JLabel lSair) {
        this.lSair = lSair;
    }

    /**
     * @return the lSenha
     */
    public javax.swing.JLabel getlSenha() {
        return lSenha;
    }

    /**
     * @param lSenha the lSenha to set
     */
    public void setlSenha(javax.swing.JLabel lSenha) {
        this.lSenha = lSenha;
    }

    /**
     * @return the lTitLogin
     */
    public javax.swing.JLabel getlTitLogin() {
        return lTitLogin;
    }

    /**
     * @param lTitLogin the lTitLogin to set
     */
    public void setlTitLogin(javax.swing.JLabel lTitLogin) {
        this.lTitLogin = lTitLogin;
    }

    /**
     * @return the lTitulo
     */
    public javax.swing.JLabel getlTitulo() {
        return lTitulo;
    }

    /**
     * @param lTitulo the lTitulo to set
     */
    public void setlTitulo(javax.swing.JLabel lTitulo) {
        this.lTitulo = lTitulo;
    }

    /**
     * @return the lUsuario
     */
    public javax.swing.JLabel getlUsuario() {
        return lUsuario;
    }

    /**
     * @param lUsuario the lUsuario to set
     */
    public void setlUsuario(javax.swing.JLabel lUsuario) {
        this.lUsuario = lUsuario;
    }

    /**
     * @return the pLibraryIcon
     */
    public javax.swing.JPanel getpLibraryIcon() {
        return pLibraryIcon;
    }

    /**
     * @param pLibraryIcon the pLibraryIcon to set
     */
    public void setpLibraryIcon(javax.swing.JPanel pLibraryIcon) {
        this.pLibraryIcon = pLibraryIcon;
    }

    /**
     * @return the pLogin
     */
    public javax.swing.JPanel getpLogin() {
        return pLogin;
    }

    /**
     * @param pLogin the pLogin to set
     */
    public void setpLogin(javax.swing.JPanel pLogin) {
        this.pLogin = pLogin;
    }

    /**
     * @return the pLoginSubmenu
     */
    public javax.swing.JPanel getpLoginSubmenu() {
        return pLoginSubmenu;
    }

    /**
     * @param pLoginSubmenu the pLoginSubmenu to set
     */
    public void setpLoginSubmenu(javax.swing.JPanel pLoginSubmenu) {
        this.pLoginSubmenu = pLoginSubmenu;
    }

    /**
     * @return the pfSenha
     */
    public javax.swing.JPasswordField getPfSenha() {
        return pfSenha;
    }

    /**
     * @param pfSenha the pfSenha to set
     */
    public void setPfSenha(javax.swing.JPasswordField pfSenha) {
        this.pfSenha = pfSenha;
    }

    /**
     * @return the taSubtitulo
     */
    public javax.swing.JTextArea getTaSubtitulo() {
        return taSubtitulo;
    }

    /**
     * @param taSubtitulo the taSubtitulo to set
     */
    public void setTaSubtitulo(javax.swing.JTextArea taSubtitulo) {
        this.taSubtitulo = taSubtitulo;
    }

    /**
     * @return the txfUsuario
     */
    public javax.swing.JTextField getTxfUsuario() {
        return txfUsuario;
    }

    /**
     * @param txfUsuario the txfUsuario to set
     */
    public void setTxfUsuario(javax.swing.JTextField txfUsuario) {
        this.txfUsuario = txfUsuario;
    }
}
