/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uemg.view;

import uemg.control.EmprestimosController;
import uemg.control.LeitoresController;
import uemg.control.LoginController;
import uemg.control.ObrasController;

/**
 *
 * @author Adalberto
 */
public class Menu extends javax.swing.JFrame {

    private LoginController control;
    private Login login;
    
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        btnObras.setFocusable(false);
        btnEmprestimos.setFocusable(false);
        btnLeitor.setFocusable(false);
        btnVoltar.setFocusable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pMenu = new javax.swing.JPanel();
        btnObras = new javax.swing.JButton();
        btnEmprestimos = new javax.swing.JButton();
        btnLeitor = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        lTitulo = new javax.swing.JLabel();
        lSair = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela de menu");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pMenu.setBackground(new java.awt.Color(102, 0, 0));

        btnObras.setBackground(new java.awt.Color(102, 0, 0));
        btnObras.setForeground(new java.awt.Color(255, 255, 255));
        btnObras.setText("OBRAS");
        btnObras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrasActionPerformed(evt);
            }
        });

        btnEmprestimos.setBackground(new java.awt.Color(102, 0, 0));
        btnEmprestimos.setForeground(new java.awt.Color(255, 255, 255));
        btnEmprestimos.setText("EMPRÉSTIMOS");
        btnEmprestimos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmprestimosActionPerformed(evt);
            }
        });

        btnLeitor.setBackground(new java.awt.Color(102, 0, 0));
        btnLeitor.setForeground(new java.awt.Color(255, 255, 255));
        btnLeitor.setText("LEITORES");
        btnLeitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeitorActionPerformed(evt);
            }
        });

        btnVoltar.setBackground(new java.awt.Color(102, 0, 0));
        btnVoltar.setForeground(new java.awt.Color(255, 255, 255));
        btnVoltar.setText("VOLTAR");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        lTitulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lTitulo.setText("Escolha um dos módulos a seguir:");

        lSair.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        lSair.setForeground(new java.awt.Color(255, 255, 255));
        lSair.setText("X");
        lSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lSairMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pMenuLayout = new javax.swing.GroupLayout(pMenu);
        pMenu.setLayout(pMenuLayout);
        pMenuLayout.setHorizontalGroup(
            pMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMenuLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(pMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pMenuLayout.createSequentialGroup()
                        .addComponent(lTitulo)
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pMenuLayout.createSequentialGroup()
                        .addGroup(pMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnVoltar)
                            .addGroup(pMenuLayout.createSequentialGroup()
                                .addComponent(btnLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(btnObras, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEmprestimos)))
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pMenuLayout.createSequentialGroup()
                        .addComponent(lSair)
                        .addGap(14, 14, 14))))
        );
        pMenuLayout.setVerticalGroup(
            pMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMenuLayout.createSequentialGroup()
                .addComponent(lSair)
                .addGap(10, 10, 10)
                .addComponent(lTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(pMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEmprestimos, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnObras, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        getContentPane().add(pMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        setSize(new java.awt.Dimension(400, 300));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        Login l = new Login();
        l.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void lSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lSairMouseClicked
        dispose();
    }//GEN-LAST:event_lSairMouseClicked

    private void btnLeitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeitorActionPerformed
        Leitores l = new Leitores();
        LeitoresController lc = new LeitoresController(l);
        
        l.setVisible(true);
        l.setLocationRelativeTo(l);
        dispose();
    }//GEN-LAST:event_btnLeitorActionPerformed

    private void btnObrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrasActionPerformed
        Obras o = new Obras();
        ObrasController oc = new ObrasController(o);
        
        o.setVisible(true);
        o.setLocationRelativeTo(o);
        dispose();
    }//GEN-LAST:event_btnObrasActionPerformed

    private void btnEmprestimosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmprestimosActionPerformed
        Emprestimos ee = new Emprestimos();
        EmprestimosController ec = new EmprestimosController(ee);
        
        ee.setVisible(true);
        ee.setLocationRelativeTo(ee);
        dispose();
    }//GEN-LAST:event_btnEmprestimosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEmprestimos;
    private javax.swing.JButton btnLeitor;
    private javax.swing.JButton btnObras;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel lSair;
    private javax.swing.JLabel lTitulo;
    private javax.swing.JPanel pMenu;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the btnEmprestimos
     */
    public javax.swing.JButton getBtnEmprestimos() {
        return btnEmprestimos;
    }

    /**
     * @param btnEmprestimos the btnEmprestimos to set
     */
    public void setBtnEmprestimos(javax.swing.JButton btnEmprestimos) {
        this.btnEmprestimos = btnEmprestimos;
    }

    /**
     * @return the btnLeitor
     */
    public javax.swing.JButton getBtnLeitor() {
        return btnLeitor;
    }

    /**
     * @param btnLeitor the btnLeitor to set
     */
    public void setBtnLeitor(javax.swing.JButton btnLeitor) {
        this.btnLeitor = btnLeitor;
    }

    /**
     * @return the btnObras
     */
    public javax.swing.JButton getBtnObras() {
        return btnObras;
    }

    /**
     * @param btnObras the btnObras to set
     */
    public void setBtnObras(javax.swing.JButton btnObras) {
        this.btnObras = btnObras;
    }

    /**
     * @return the btnVoltar
     */
    public javax.swing.JButton getBtnVoltar() {
        return btnVoltar;
    }

    /**
     * @param btnVoltar the btnVoltar to set
     */
    public void setBtnVoltar(javax.swing.JButton btnVoltar) {
        this.btnVoltar = btnVoltar;
    }

    /**
     * @return the lSair
     */
    public javax.swing.JLabel getlSair() {
        return lSair;
    }

    /**
     * @param lSair the lSair to set
     */
    public void setlSair(javax.swing.JLabel lSair) {
        this.lSair = lSair;
    }

    /**
     * @return the lTitulo
     */
    public javax.swing.JLabel getlTitulo() {
        return lTitulo;
    }

    /**
     * @param lTitulo the lTitulo to set
     */
    public void setlTitulo(javax.swing.JLabel lTitulo) {
        this.lTitulo = lTitulo;
    }

    /**
     * @return the pMenu
     */
    public javax.swing.JPanel getpMenu() {
        return pMenu;
    }

    /**
     * @param pMenu the pMenu to set
     */
    public void setpMenu(javax.swing.JPanel pMenu) {
        this.pMenu = pMenu;
    }

    /**
     * @return the control
     */
    public LoginController getControl() {
        return control;
    }

    /**
     * @param control the control to set
     */
    public void setControl(LoginController control) {
        this.control = control;
    }

    /**
     * @return the login
     */
    public Login getLogin() {
        return login;
    }

    /**
     * @param login the login to set
     */
    public void setLogin(Login login) {
        this.login = login;
    }
}
