package uemg.view;

import uemg.control.ObrasController;

public class Obras extends javax.swing.JFrame {

    public Obras() {
        initComponents();
        btnEditar.setFocusable(false);
        btnExcluir.setFocusable(false);
        btnGravar.setFocusable(false);
        btnExcluir.setFocusable(false);
        btnSelect.setFocusable(false);
        btnVoltar.setFocusable(false);
        btnOk.setFocusable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        pLeitores = new javax.swing.JPanel();
        lSair = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        pDados = new javax.swing.JPanel();
        lExemplares = new javax.swing.JLabel();
        lTipoPeriodico = new javax.swing.JLabel();
        lAutor = new javax.swing.JLabel();
        lEdicao = new javax.swing.JLabel();
        lCidade = new javax.swing.JLabel();
        lEditora = new javax.swing.JLabel();
        lPaginas = new javax.swing.JLabel();
        lCm = new javax.swing.JLabel();
        lIsbn = new javax.swing.JLabel();
        lCdu = new javax.swing.JLabel();
        lPalavrasChave = new javax.swing.JLabel();
        lNomeObra = new javax.swing.JLabel();
        lCatPeriodico = new javax.swing.JLabel();
        txfEditora = new javax.swing.JTextField();
        txfTipoPeriodico = new javax.swing.JTextField();
        txfPalavraChave = new javax.swing.JTextField();
        txfAutor = new javax.swing.JTextField();
        txfEdicao = new javax.swing.JTextField();
        txfCidade = new javax.swing.JTextField();
        txfNomeObra = new javax.swing.JTextField();
        txfPaginas = new javax.swing.JTextField();
        txfCm = new javax.swing.JTextField();
        txfExemplares = new javax.swing.JTextField();
        ftfCdu = new javax.swing.JFormattedTextField();
        ftfIsbn = new javax.swing.JFormattedTextField();
        lAno = new javax.swing.JLabel();
        txfAno = new javax.swing.JTextField();
        txfCategoriaPedido = new javax.swing.JTextField();
        pRegistros = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dgObras = new javax.swing.JTable();
        pOperacoes = new javax.swing.JPanel();
        btnOk = new javax.swing.JButton();
        btnGravar = new javax.swing.JButton();
        btnSelect = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pLeitores.setBackground(new java.awt.Color(102, 0, 0));
        pLeitores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lSair.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        lSair.setForeground(new java.awt.Color(255, 255, 255));
        lSair.setText("X");
        lSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lSairMouseClicked(evt);
            }
        });
        pLeitores.add(lSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(735, 0, -1, -1));

        btnVoltar.setBackground(new java.awt.Color(102, 0, 0));
        btnVoltar.setForeground(new java.awt.Color(255, 255, 255));
        btnVoltar.setText("VOLTAR");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        pLeitores.add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 604, -1, 32));

        pDados.setBackground(new java.awt.Color(102, 0, 0));
        pDados.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        pDados.setForeground(new java.awt.Color(255, 255, 255));
        pDados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lExemplares.setForeground(new java.awt.Color(255, 255, 255));
        lExemplares.setText("Exemplares:");
        pDados.add(lExemplares, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, -1, -1));

        lTipoPeriodico.setForeground(new java.awt.Color(255, 255, 255));
        lTipoPeriodico.setText("Tipo do periódico:");
        pDados.add(lTipoPeriodico, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        lAutor.setForeground(new java.awt.Color(255, 255, 255));
        lAutor.setText("Autor:");
        pDados.add(lAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        lEdicao.setForeground(new java.awt.Color(255, 255, 255));
        lEdicao.setText("Edição:");
        pDados.add(lEdicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        lCidade.setForeground(new java.awt.Color(255, 255, 255));
        lCidade.setText("Cidade:");
        pDados.add(lCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        lEditora.setForeground(new java.awt.Color(255, 255, 255));
        lEditora.setText("Editora:");
        pDados.add(lEditora, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        lPaginas.setForeground(new java.awt.Color(255, 255, 255));
        lPaginas.setText("Páginas:");
        pDados.add(lPaginas, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, -1, -1));

        lCm.setForeground(new java.awt.Color(255, 255, 255));
        lCm.setText("CM:");
        pDados.add(lCm, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, -1, -1));

        lIsbn.setForeground(new java.awt.Color(255, 255, 255));
        lIsbn.setText("ISBN:");
        pDados.add(lIsbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, -1, -1));

        lCdu.setForeground(new java.awt.Color(255, 255, 255));
        lCdu.setText("CDU:");
        pDados.add(lCdu, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, -1, -1));

        lPalavrasChave.setForeground(new java.awt.Color(255, 255, 255));
        lPalavrasChave.setText("Palavras-chave:");
        pDados.add(lPalavrasChave, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        lNomeObra.setForeground(new java.awt.Color(255, 255, 255));
        lNomeObra.setText("Nome da obra:");
        pDados.add(lNomeObra, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, 20));

        lCatPeriodico.setForeground(new java.awt.Color(255, 255, 255));
        lCatPeriodico.setText("Categoria do periódico:");
        pDados.add(lCatPeriodico, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        txfEditora.setBackground(new java.awt.Color(102, 0, 0));
        txfEditora.setForeground(new java.awt.Color(255, 255, 255));
        txfEditora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfEditoraActionPerformed(evt);
            }
        });
        pDados.add(txfEditora, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 210, -1));

        txfTipoPeriodico.setBackground(new java.awt.Color(102, 0, 0));
        txfTipoPeriodico.setForeground(new java.awt.Color(255, 255, 255));
        txfTipoPeriodico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfTipoPeriodicoActionPerformed(evt);
            }
        });
        pDados.add(txfTipoPeriodico, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 200, -1));

        txfPalavraChave.setBackground(new java.awt.Color(102, 0, 0));
        txfPalavraChave.setForeground(new java.awt.Color(255, 255, 255));
        txfPalavraChave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfPalavraChaveActionPerformed(evt);
            }
        });
        pDados.add(txfPalavraChave, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 420, -1));

        txfAutor.setBackground(new java.awt.Color(102, 0, 0));
        txfAutor.setForeground(new java.awt.Color(255, 255, 255));
        txfAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfAutorActionPerformed(evt);
            }
        });
        pDados.add(txfAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 210, -1));

        txfEdicao.setBackground(new java.awt.Color(102, 0, 0));
        txfEdicao.setForeground(new java.awt.Color(255, 255, 255));
        txfEdicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfEdicaoActionPerformed(evt);
            }
        });
        pDados.add(txfEdicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 210, -1));

        txfCidade.setBackground(new java.awt.Color(102, 0, 0));
        txfCidade.setForeground(new java.awt.Color(255, 255, 255));
        txfCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfCidadeActionPerformed(evt);
            }
        });
        pDados.add(txfCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 210, -1));

        txfNomeObra.setBackground(new java.awt.Color(102, 0, 0));
        txfNomeObra.setForeground(new java.awt.Color(255, 255, 255));
        txfNomeObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfNomeObraActionPerformed(evt);
            }
        });
        pDados.add(txfNomeObra, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 210, -1));

        txfPaginas.setBackground(new java.awt.Color(102, 0, 0));
        txfPaginas.setForeground(new java.awt.Color(255, 255, 255));
        txfPaginas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfPaginasActionPerformed(evt);
            }
        });
        pDados.add(txfPaginas, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 110, -1));

        txfCm.setBackground(new java.awt.Color(102, 0, 0));
        txfCm.setForeground(new java.awt.Color(255, 255, 255));
        txfCm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfCmActionPerformed(evt);
            }
        });
        pDados.add(txfCm, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 110, -1));

        txfExemplares.setBackground(new java.awt.Color(102, 0, 0));
        txfExemplares.setForeground(new java.awt.Color(255, 255, 255));
        txfExemplares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfExemplaresActionPerformed(evt);
            }
        });
        pDados.add(txfExemplares, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 110, -1));

        ftfCdu.setBackground(new java.awt.Color(102, 0, 0));
        ftfCdu.setForeground(new java.awt.Color(255, 255, 255));
        try {
            ftfCdu.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.##:###.##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        pDados.add(ftfCdu, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 110, -1));

        ftfIsbn.setBackground(new java.awt.Color(102, 0, 0));
        ftfIsbn.setForeground(new java.awt.Color(255, 255, 255));
        try {
            ftfIsbn.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-####-###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        pDados.add(ftfIsbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 110, -1));

        lAno.setForeground(new java.awt.Color(255, 255, 255));
        lAno.setText("Ano:");
        pDados.add(lAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, -1, -1));

        txfAno.setBackground(new java.awt.Color(102, 0, 0));
        txfAno.setForeground(new java.awt.Color(255, 255, 255));
        txfAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfAnoActionPerformed(evt);
            }
        });
        pDados.add(txfAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 110, -1));

        txfCategoriaPedido.setBackground(new java.awt.Color(102, 0, 0));
        txfCategoriaPedido.setForeground(new java.awt.Color(255, 255, 255));
        txfCategoriaPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfCategoriaPedidoActionPerformed(evt);
            }
        });
        pDados.add(txfCategoriaPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 170, -1));

        pLeitores.add(pDados, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 560, 310));

        pRegistros.setBackground(new java.awt.Color(102, 0, 0));
        pRegistros.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registros", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        pRegistros.setForeground(new java.awt.Color(255, 255, 255));
        pRegistros.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dgObras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo do periódico", "Categoria do periódico", "Nome da obra", "Autor", "Edição", "Cidade", "Editora", "Páginas", "CM", "ISBN", "CDU", "Exemplares", "Ano", "Palavras-chave"
            }
        ));
        jScrollPane1.setViewportView(dgObras);

        pRegistros.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 730, 200));

        pLeitores.add(pRegistros, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 750, 230));

        pOperacoes.setBackground(new java.awt.Color(102, 0, 0));
        pOperacoes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Operações", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        pOperacoes.setForeground(new java.awt.Color(255, 255, 255));

        btnOk.setBackground(new java.awt.Color(102, 0, 0));
        btnOk.setForeground(new java.awt.Color(255, 255, 255));
        btnOk.setText("OK");

        btnGravar.setBackground(new java.awt.Color(102, 0, 0));
        btnGravar.setForeground(new java.awt.Color(255, 255, 255));
        btnGravar.setText("GRAVAR");

        btnSelect.setBackground(new java.awt.Color(102, 0, 0));
        btnSelect.setForeground(new java.awt.Color(255, 255, 255));
        btnSelect.setText("PESQUISAR");

        btnEditar.setBackground(new java.awt.Color(102, 0, 0));
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setText("EDITAR");

        btnExcluir.setBackground(new java.awt.Color(102, 0, 0));
        btnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluir.setText("EXCLUIR");

        javax.swing.GroupLayout pOperacoesLayout = new javax.swing.GroupLayout(pOperacoes);
        pOperacoes.setLayout(pOperacoesLayout);
        pOperacoesLayout.setHorizontalGroup(
            pOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pOperacoesLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(pOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSelect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGravar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnOk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );
        pOperacoesLayout.setVerticalGroup(
            pOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pOperacoesLayout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(btnOk)
                .addGap(17, 17, 17)
                .addComponent(btnGravar)
                .addGap(17, 17, 17)
                .addComponent(btnSelect)
                .addGap(17, 17, 17)
                .addComponent(btnEditar)
                .addGap(17, 17, 17)
                .addComponent(btnExcluir)
                .addGap(50, 50, 50))
        );

        pLeitores.add(pOperacoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 40, 180, 310));

        getContentPane().add(pLeitores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 650));

        setSize(new java.awt.Dimension(768, 647));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lSairMouseClicked
        dispose();
    }//GEN-LAST:event_lSairMouseClicked

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        Menu m = new Menu();
        m.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void txfEditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfEditoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfEditoraActionPerformed

    private void txfTipoPeriodicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfTipoPeriodicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfTipoPeriodicoActionPerformed

    private void txfPalavraChaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfPalavraChaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfPalavraChaveActionPerformed

    private void txfAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfAutorActionPerformed

    private void txfEdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfEdicaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfEdicaoActionPerformed

    private void txfCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfCidadeActionPerformed

    private void txfNomeObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfNomeObraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfNomeObraActionPerformed

    private void txfPaginasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfPaginasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfPaginasActionPerformed

    private void txfCmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfCmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfCmActionPerformed

    private void txfExemplaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfExemplaresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfExemplaresActionPerformed

    private void txfAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfAnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfAnoActionPerformed

    private void txfCategoriaPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfCategoriaPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfCategoriaPedidoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnEditar;
    public javax.swing.JButton btnExcluir;
    public javax.swing.JButton btnGravar;
    public javax.swing.JButton btnOk;
    public javax.swing.JButton btnSelect;
    private javax.swing.JButton btnVoltar;
    public javax.swing.JTable dgObras;
    public javax.swing.JFormattedTextField ftfCdu;
    public javax.swing.JFormattedTextField ftfIsbn;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lAno;
    private javax.swing.JLabel lAutor;
    private javax.swing.JLabel lCatPeriodico;
    private javax.swing.JLabel lCdu;
    private javax.swing.JLabel lCidade;
    private javax.swing.JLabel lCm;
    private javax.swing.JLabel lEdicao;
    private javax.swing.JLabel lEditora;
    private javax.swing.JLabel lExemplares;
    private javax.swing.JLabel lIsbn;
    private javax.swing.JLabel lNomeObra;
    private javax.swing.JLabel lPaginas;
    private javax.swing.JLabel lPalavrasChave;
    private javax.swing.JLabel lSair;
    private javax.swing.JLabel lTipoPeriodico;
    private javax.swing.JPanel pDados;
    private javax.swing.JPanel pLeitores;
    private javax.swing.JPanel pOperacoes;
    private javax.swing.JPanel pRegistros;
    public javax.swing.JTextField txfAno;
    public javax.swing.JTextField txfAutor;
    public javax.swing.JTextField txfCategoriaPedido;
    public javax.swing.JTextField txfCidade;
    public javax.swing.JTextField txfCm;
    public javax.swing.JTextField txfEdicao;
    public javax.swing.JTextField txfEditora;
    public javax.swing.JTextField txfExemplares;
    public javax.swing.JTextField txfNomeObra;
    public javax.swing.JTextField txfPaginas;
    public javax.swing.JTextField txfPalavraChave;
    public javax.swing.JTextField txfTipoPeriodico;
    // End of variables declaration//GEN-END:variables

}
